name: Go Test and Build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pulse_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'

      - name: Check Formatting
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "The following files are not formatted:"
            gofmt -l .
            exit 1
          fi

      - name: Go Vet
        run: go vet ./...

      - name: Run Tests
        env:
          TEST_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_pulse_db
        run: go test -v ./...

      - name: Build Binary
        run: CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o pulse-api ./cmd/api

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-binary
          path: pulse-api
          retention-days: 1